//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pip_air.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiskets
    {
        public int Id { get; set; }
        public int Num_flight { get; set; }
        public int Sum_place { get; set; }
        public Nullable<int> Sum_rezerved { get; set; }
        public Nullable<int> Sum_bought { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
